# This is a generated file. Not intended for manual editing.
services:
  hrmanagerwebapp:
    build:
      context: "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5"
      dockerfile: "HRManagerWebApp/HRManagerWebApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/HRManagerWebApp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "hrmanagerwebapp:dev"
    ports: []
    volumes:
    - "C:\\Users\\Dmitry\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5\\HRManagerWebApp\\HRManagerWebApp:/app:rw"
    - "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5\\HRManagerWebApp:/src:rw"
    working_dir: "/app"
