# This is a generated file. Not intended for manual editing.
services:
  hrdirectorwebapp:
    build:
      context: "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5"
      dockerfile: "HRDirectorWebApp/HRDirectorWebApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/HRDirectorWebApp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "hrdirectorwebapp:dev"
    ports: []
    volumes:
    - "C:\\Users\\Dmitry\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5\\HRDirectorWebApp\\HRDirectorWebApp:/app:rw"
    - "C:\\Users\\Dmitry\\RiderProjects\\HackathonLabs\\Lab5\\HRDirectorWebApp:/src:rw"
    working_dir: "/app"
